#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Collections;
using System.Collections.Generic;
using System.Data;

using ERPConnect;
using ERPConnect.BW;
using ERPConnect.Idocs;
using ERPConnect.Linq;
using ERPConnect.Queries;

namespace ERPCDemoke01
{
	public partial class SAPContext : ERPDataContext
	{
		public SAPContext()
		{
		}

		public SAPContext(string username, string password)
			: base(string.Format(@"USER=""{0}"" PASSWD=""{1}"" LANG=DE CLIENT=800 ASHOST=ec5.theobald-software.com SYSNR=00", username, password))
		{
		}

		public SAPContext(string connectionString)
			: base(connectionString)
		{
		}

		public SAPContext(string host, int system, string username, string password, string language, string client)
			: base(host, system, username, password, language, client)
		{
		}

		public SAPContext(string httpUrl, string username, string password, string language, string client)
			: base(httpUrl, username, password, language, client)
		{
		}

		public SAPContext(string messageServer, string SID, string logonGroup, string username, string password, string language, string client)
			: base(string.Format(@"MSHOST=""{0}"" R3NAME=""{1}"" GROUP=""{2}"" USER=""{3}"" PASSWD=""{4}"" LANG=""{5}"" CLIENT=""{6}""", messageServer, SID, logonGroup, username, password, language, client))
		{
		}

		/// <summary>
		/// Ändert eine Anlage
		/// </summary>
		public void BAPI_FIXEDASSET_CHANGE(string ASSET, string COMPANYCODE, GENERALDATAStructure GENERALDATA, GENERALDATAXStructure GENERALDATAX, string SUBNUMBER)
		{
			if(!Connection.Ping()) Connection.Open();

			RFCFunction function = Connection.CreateFunction("BAPI_FIXEDASSET_CHANGE");

			function.Exports["ASSET"].ParamValue = ASSET;
			function.Exports["COMPANYCODE"].ParamValue = COMPANYCODE;
			function.Exports["GENERALDATA"].ParamValue = GENERALDATA.Structure;
			function.Exports["GENERALDATAX"].ParamValue = GENERALDATAX.Structure;
			function.Exports["SUBNUMBER"].ParamValue = SUBNUMBER;

			function.Execute();

		}

		public partial class GENERALDATAStructure
		{
			RFCStructure _structure;

			[Browsable(false)]
			public RFCStructure Structure
			{
				get { return _structure; }
			}

			public string ASSETCLASS
			{
				get { return (string)_structure["ASSETCLASS"]; }
				set { _structure["ASSETCLASS"] = value; }
			}

			public string DESCRIPT
			{
				get { return (string)_structure["DESCRIPT"]; }
				set { _structure["DESCRIPT"] = value; }
			}

			public string DESCRIPT2
			{
				get { return (string)_structure["DESCRIPT2"]; }
				set { _structure["DESCRIPT2"] = value; }
			}

			public string ACCT_DETRM
			{
				get { return (string)_structure["ACCT_DETRM"]; }
				set { _structure["ACCT_DETRM"] = value; }
			}

			public string SERIAL_NO
			{
				get { return (string)_structure["SERIAL_NO"]; }
				set { _structure["SERIAL_NO"] = value; }
			}

			public string INVENT_NO
			{
				get { return (string)_structure["INVENT_NO"]; }
				set { _structure["INVENT_NO"] = value; }
			}

			public decimal QUANTITY
			{
				get { return (decimal)_structure["QUANTITY"]; }
				set { _structure["QUANTITY"] = value; }
			}

			public string BASE_UOM
			{
				get { return (string)_structure["BASE_UOM"]; }
				set { _structure["BASE_UOM"] = value; }
			}

			public string BASE_UOM_ISO
			{
				get { return (string)_structure["BASE_UOM_ISO"]; }
				set { _structure["BASE_UOM_ISO"] = value; }
			}

			public string HISTORY
			{
				get { return (string)_structure["HISTORY"]; }
				set { _structure["HISTORY"] = value; }
			}

			public string MAIN_DESCRIPT
			{
				get { return (string)_structure["MAIN_DESCRIPT"]; }
				set { _structure["MAIN_DESCRIPT"] = value; }
			}

			public GENERALDATAStructure()
			{
				RFCTableColumnCollection collection = new RFCTableColumnCollection();
				collection.FixedLength = 440;
				collection.ABAPStructureName = "BAPI1022_FEGLG001";
				RFCTableColumn c = null;
				c = new RFCTableColumn("ASSETCLASS", 16, 0, RFCTYPE.CHAR);
				c.Offset = 0;
				c.IsNonStructureLineType = false;
				collection.Add(c);
				c = new RFCTableColumn("DESCRIPT", 100, 0, RFCTYPE.CHAR);
				c.Offset = 16;
				c.IsNonStructureLineType = false;
				collection.Add(c);
				c = new RFCTableColumn("DESCRIPT2", 100, 0, RFCTYPE.CHAR);
				c.Offset = 116;
				c.IsNonStructureLineType = false;
				collection.Add(c);
				c = new RFCTableColumn("ACCT_DETRM", 16, 0, RFCTYPE.CHAR);
				c.Offset = 216;
				c.IsNonStructureLineType = false;
				collection.Add(c);
				c = new RFCTableColumn("SERIAL_NO", 36, 0, RFCTYPE.CHAR);
				c.Offset = 232;
				c.IsNonStructureLineType = false;
				collection.Add(c);
				c = new RFCTableColumn("INVENT_NO", 50, 0, RFCTYPE.CHAR);
				c.Offset = 268;
				c.IsNonStructureLineType = false;
				collection.Add(c);
				c = new RFCTableColumn("QUANTITY", 7, 3, RFCTYPE.BCD);
				c.Offset = 318;
				c.IsNonStructureLineType = false;
				collection.Add(c);
				c = new RFCTableColumn("BASE_UOM", 6, 0, RFCTYPE.CHAR);
				c.Offset = 326;
				c.IsNonStructureLineType = false;
				collection.Add(c);
				c = new RFCTableColumn("BASE_UOM_ISO", 6, 0, RFCTYPE.CHAR);
				c.Offset = 332;
				c.IsNonStructureLineType = false;
				collection.Add(c);
				c = new RFCTableColumn("HISTORY", 2, 0, RFCTYPE.CHAR);
				c.Offset = 338;
				c.IsNonStructureLineType = false;
				collection.Add(c);
				c = new RFCTableColumn("MAIN_DESCRIPT", 100, 0, RFCTYPE.CHAR);
				c.Offset = 340;
				c.IsNonStructureLineType = false;
				collection.Add(c);

				_structure = new RFCStructure(collection);

			}

			public GENERALDATAStructure(RFCStructure structure)
			{
				_structure = structure;
			}
		}

		public partial class GENERALDATAXStructure
		{
			RFCStructure _structure;

			[Browsable(false)]
			public RFCStructure Structure
			{
				get { return _structure; }
			}

			public string ASSETCLASS
			{
				get { return (string)_structure["ASSETCLASS"]; }
				set { _structure["ASSETCLASS"] = value; }
			}

			public string DESCRIPT
			{
				get { return (string)_structure["DESCRIPT"]; }
				set { _structure["DESCRIPT"] = value; }
			}

			public string DESCRIPT2
			{
				get { return (string)_structure["DESCRIPT2"]; }
				set { _structure["DESCRIPT2"] = value; }
			}

			public string ACCT_DETRM
			{
				get { return (string)_structure["ACCT_DETRM"]; }
				set { _structure["ACCT_DETRM"] = value; }
			}

			public string SERIAL_NO
			{
				get { return (string)_structure["SERIAL_NO"]; }
				set { _structure["SERIAL_NO"] = value; }
			}

			public string INVENT_NO
			{
				get { return (string)_structure["INVENT_NO"]; }
				set { _structure["INVENT_NO"] = value; }
			}

			public string QUANTITY
			{
				get { return (string)_structure["QUANTITY"]; }
				set { _structure["QUANTITY"] = value; }
			}

			public string BASE_UOM
			{
				get { return (string)_structure["BASE_UOM"]; }
				set { _structure["BASE_UOM"] = value; }
			}

			public string BASE_UOM_ISO
			{
				get { return (string)_structure["BASE_UOM_ISO"]; }
				set { _structure["BASE_UOM_ISO"] = value; }
			}

			public string HISTORY
			{
				get { return (string)_structure["HISTORY"]; }
				set { _structure["HISTORY"] = value; }
			}

			public string MAIN_DESCRIPT
			{
				get { return (string)_structure["MAIN_DESCRIPT"]; }
				set { _structure["MAIN_DESCRIPT"] = value; }
			}

			public GENERALDATAXStructure()
			{
				RFCTableColumnCollection collection = new RFCTableColumnCollection();
				collection.FixedLength = 22;
				collection.ABAPStructureName = "BAPI1022_FEGLG001X";
				RFCTableColumn c = null;
				c = new RFCTableColumn("ASSETCLASS", 2, 0, RFCTYPE.CHAR);
				c.Offset = 0;
				c.IsNonStructureLineType = false;
				collection.Add(c);
				c = new RFCTableColumn("DESCRIPT", 2, 0, RFCTYPE.CHAR);
				c.Offset = 2;
				c.IsNonStructureLineType = false;
				collection.Add(c);
				c = new RFCTableColumn("DESCRIPT2", 2, 0, RFCTYPE.CHAR);
				c.Offset = 4;
				c.IsNonStructureLineType = false;
				collection.Add(c);
				c = new RFCTableColumn("ACCT_DETRM", 2, 0, RFCTYPE.CHAR);
				c.Offset = 6;
				c.IsNonStructureLineType = false;
				collection.Add(c);
				c = new RFCTableColumn("SERIAL_NO", 2, 0, RFCTYPE.CHAR);
				c.Offset = 8;
				c.IsNonStructureLineType = false;
				collection.Add(c);
				c = new RFCTableColumn("INVENT_NO", 2, 0, RFCTYPE.CHAR);
				c.Offset = 10;
				c.IsNonStructureLineType = false;
				collection.Add(c);
				c = new RFCTableColumn("QUANTITY", 2, 0, RFCTYPE.CHAR);
				c.Offset = 12;
				c.IsNonStructureLineType = false;
				collection.Add(c);
				c = new RFCTableColumn("BASE_UOM", 2, 0, RFCTYPE.CHAR);
				c.Offset = 14;
				c.IsNonStructureLineType = false;
				collection.Add(c);
				c = new RFCTableColumn("BASE_UOM_ISO", 2, 0, RFCTYPE.CHAR);
				c.Offset = 16;
				c.IsNonStructureLineType = false;
				collection.Add(c);
				c = new RFCTableColumn("HISTORY", 2, 0, RFCTYPE.CHAR);
				c.Offset = 18;
				c.IsNonStructureLineType = false;
				collection.Add(c);
				c = new RFCTableColumn("MAIN_DESCRIPT", 2, 0, RFCTYPE.CHAR);
				c.Offset = 20;
				c.IsNonStructureLineType = false;
				collection.Add(c);

				_structure = new RFCStructure(collection);

			}

			public GENERALDATAXStructure(RFCStructure structure)
			{
				_structure = structure;
			}
		}
	}
}
#pragma warning restore 1591
