// This is a Javascript test harness that simulates the execution of Lambda function code
// From the command prompt, type "node test.js"

const MyLambdaFunction = require('../custom/index.js'); // assumes single Lambda function with exports.handler

 // this is the Lambda request data, generated by the Alexa service.  Replace with your actual Alexa request.
let event =
    {
        "session": {
            "sessionId": "SessionId.f9e6dcbb-b7da-4b47-905c.etc.etc",
            "application": {
                "applicationId": "amzn1.echo-sdk-ams.app.1234"
            },
            "attributes":{        
                "customerResult": {
                    "Customers": [
                        {
                            "CustomerNumber": "0000000307",
                            "CustomerName": "Los Pollos Hermanos Inc"
                        },
                        {
                            "CustomerNumber": "0000003070",
                            "CustomerName": "William G. Smith MD"
                        },
                        {
                            "CustomerNumber": "0000003071",
                            "CustomerName": "Walter G. Baldwin"
                        }
                    ],
                    "CustomerCount": "3"
                }            
        },
            "user": {
                "userId": "amzn1.ask.account.VO3PVTGF563MOPBY.etc.etc"
            },
            "new": true
        },
        "request": {
            "type": "IntentRequest",
            "requestId": "request5678",
            "locale": "en-US",
            "intent": {
                "name": "SelectCustomerIndexIntent",
                "confirmationStatus": "NONE",
                "slots": {
                  "selectedcustomerindex": {
                    "name": "selectedcustomerindex",
                    "value": "2",
                    "confirmationStatus": "NONE",
                    "source": "USER"
                  }
                }
            }
        },
        "version": "1.0"
    };

let context = {
    'succeed': function (data) {
        console.log(JSON.stringify(data, null,'\t') );

    },
    'fail': function (err) {
        console.log('context.fail occurred');
        console.log(JSON.stringify(err, null,'\t') );
    }

};

function callback(error, data) {
    if(error) {
        console.log('error: ' + error);
    } else {
        console.log(data);
    }
}

// call the function
MyLambdaFunction['handler'] (event, context, callback);
